### PR TITLE
Query formatting.

### PR DESCRIPTION
**Pull request by lenguyenthedat**
Sorry for the large PR, I hope this help making the queries easier to read and to debug.
Please help reviewing if possible!

I also noticed that some of the queries originally aren't working, will fix it in the next PR.

### CODE REVIEW

**Comment by joeharris76** [comment]
This is a nice change IMO. Queries are much more readable. Not sure dropping the semicolons is a good idea.

**Comment by lenguyenthedat** [comment]
@joeharris76 thanks.
It's quite out-dated now, but I'm happy to update the PR (if it has any chance of getting reviewed or merged :smile: )

**Comment by IanMeyers** [comment]
Open to merging this in, but the amount of change was so high as to make it very difficult to assess the impact, if any, on changed meaning of the queries. Would you be open to breaking this up into smaller PR's?

**Comment by lenguyenthedat** [comment]
Sure, will do!

**Comment by chriz-bigdata** [comment]
Closing due to inactivity.

**Pull request closed without merging**
