### PR TITLE
fixed edge case for default privileges

### PR DESCRIPTION
**Pull request by adedotua**
fixed one more edge case where default privilege is granted on schema to user other than schema owner

By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.

### CODE REVIEW

**Comment by adedotua** [comment]
last one today i promise ;)

**Comment by IanMeyers** [comment]
Keep the good stuff coming!

**Comment by jvogelbc** [comment]
Stumbled upon these scripts while trying to figure out how to clean up some permissions. Your admin scripts are very helpful. Quick question - how do I handle Default ACL grants with empty ACL? "Regrant privileges on tables to owner" is not clear to me.

**Comment by adedotua** [comment]
@jvogelbc, are you using the latest version of the view? There is some SQL to handle these empty ACLs and return the necessary DDL. It is the last part of the UNION ALL.


```
-- Eliminate empty default ACLs
SELECT null::text AS objowner, trim(c.nspname)::text AS schemaname, decode(b.defaclobjtype,'r','tables','f','functions')::text AS objname,
		'default acl'::text AS objtype,  pg_get_userbyid(b.defacluser)::text AS grantor, null::text AS grantee, 'revoke'::text AS ddltype, 5 as grantseq, 5 AS objseq,
  'ALTER DEFAULT PRIVILEGES for user '||QUOTE_IDENT(pg_get_userbyid(b.defacluser))||nvl(' in schema '||QUOTE_IDENT(trim(c.nspname))||' ',' ')
||'GRANT ALL on '||decode(b.defaclobjtype,'r','tables','f','functions')||' TO '||QUOTE_IDENT(pg_get_userbyid(b.defacluser))||
CASE WHEN b.defaclobjtype = 'f' then ', PUBLIC;' ELSE ';' END::text AS ddl 
		FROM pg_default_acl b 
		LEFT JOIN  pg_namespace c on b.defaclnamespace = c.oid
		where EXISTS (select 1 where b.defaclacl='{}'::aclitem[]
		UNION ALL
select 1 WHERE array_to_string(b.defaclacl,'')=('=X/'||QUOTE_IDENT(pg_get_userbyid(b.defacluser)))); 
```

**Pull request merged**
